"""Added company phone

Revision ID: 1b0eb2826949
Revises: adac1d67474d
Create Date: 2025-09-18 11:39:26.086137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b0eb2826949"
down_revision: Union[str, Sequence[str], None] = "adac1d67474d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("phone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "phone")
    # ### end Alembic commands ###
