"""MFO Partner code

Revision ID: 35114b4e4c53
Revises: 496e8a6a2af3
Create Date: 2025-09-15 16:51:47.289532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35114b4e4c53"
down_revision: Union[str, Sequence[str], None] = "496e8a6a2af3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mfo_configs", sa.Column("partner_code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mfo_configs", "partner_code")
    # ### end Alembic commands ###
