"""FPAY

Revision ID: 435a3e9a88ea
Revises: a442f116d327
Create Date: 2025-09-24 15:36:18.904493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435a3e9a88ea'
down_revision: Union[str, Sequence[str], None] = 'a442f116d327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('freedom_order_reference_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('freedom_receipt_number', sa.String(), nullable=True))
    op.create_index('ix_transactions_freedom_order_reference_id', 'transactions', ['freedom_order_reference_id'], unique=False)
    op.create_index('ix_transactions_status_created_at', 'transactions', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status_created_at', table_name='transactions')
    op.drop_index('ix_transactions_freedom_order_reference_id', table_name='transactions')
    op.drop_column('transactions', 'freedom_receipt_number')
    op.drop_column('transactions', 'freedom_order_reference_id')
    # ### end Alembic commands ###
