"""Added CMS models

Revision ID: 47bc2f712fd7
Revises: b62e80841c1b
Create Date: 2025-09-05 16:38:29.323852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47bc2f712fd7"
down_revision: Union[str, Sequence[str], None] = "b62e80841c1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_site",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=True),
        sa.Column("site_preffix", sa.String(), nullable=True),
        sa.Column("site_suffix", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_preffix"),
        sa.UniqueConstraint("site_suffix"),
    )
    op.create_index(op.f("ix_merchant_site_id"), "merchant_site", ["id"], unique=False)
    op.create_table(
        "merchant_site_carousel_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_site_id", sa.UUID(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_site_id"],
            ["merchant_site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_site_carousel_items_id"),
        "merchant_site_carousel_items",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_merchant_site_carousel_items_id"),
        table_name="merchant_site_carousel_items",
    )
    op.drop_table("merchant_site_carousel_items")
    op.drop_index(op.f("ix_merchant_site_id"), table_name="merchant_site")
    op.drop_table("merchant_site")
    # ### end Alembic commands ###
