"""Added apply code into loan_request


Revision ID: 496e8a6a2af3
Revises: acb1d41a0858
Create Date: 2025-09-15 15:34:35.863921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "496e8a6a2af3"
down_revision: Union[str, Sequence[str], None] = "acb1d41a0858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loan_requests", sa.Column("apply_code", sa.String(), nullable=True))
    op.alter_column("loan_requests", "iin", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("loan_requests", "iin", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("loan_requests", "apply_code")
    # ### end Alembic commands ###
