"""Additional Import

Revision ID: 4a5cf49f34c9
Revises: 74ec8ac86ff3
Create Date: 2025-08-29 17:36:21.178111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4a5cf49f34c9"
down_revision: Union[str, Sequence[str], None] = "74ec8ac86ff3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("saleor_order_id", sa.String(), nullable=False),
        sa.Column("synced", sa.Boolean(), nullable=True),
        sa.Column("payment_method_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["merchant_payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_table(
        "card_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("redirect_url", sa.String(), nullable=True),
        sa.Column("fallback_url", sa.String(), nullable=True),
        sa.Column("status_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_requests_id"), "card_requests", ["id"], unique=False)
    op.create_table(
        "loan_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("redirect_url", sa.String(), nullable=True),
        sa.Column("fallback_url", sa.String(), nullable=True),
        sa.Column("status_url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("iin", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loan_requests_id"), "loan_requests", ["id"], unique=False)
    op.create_table(
        "loan_offers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("loan_request_id", sa.String(), nullable=False),
        sa.Column("loan_type", sa.String(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("suitable", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["loan_request_id"],
            ["loan_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loan_offers_id"), "loan_offers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_offers_id"), table_name="loan_offers")
    op.drop_table("loan_offers")
    op.drop_index(op.f("ix_loan_requests_id"), table_name="loan_requests")
    op.drop_table("loan_requests")
    op.drop_index(op.f("ix_card_requests_id"), table_name="card_requests")
    op.drop_table("card_requests")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
