"""MFO request mobile phone

Revision ID: 4f4b52d86cfc
Revises: f19ef672e140
Create Date: 2025-09-16 15:11:29.008676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f4b52d86cfc"
down_revision: Union[str, Sequence[str], None] = "f19ef672e140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loan_requests", sa.Column("mobile_phone", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loan_requests", "mobile_phone")
    # ### end Alembic commands ###
