"""Relations of Wareouses

Revision ID: 54a923d9674e
Revises: f1fd3460f2f0
Create Date: 2025-09-08 14:58:43.912689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54a923d9674e"
down_revision: Union[str, Sequence[str], None] = "f1fd3460f2f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchant_shipping_zone", sa.Column("warehouse_id", sa.String(), nullable=True)
    )
    op.add_column(
        "merchant_shipping_zone", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "merchant_shipping_zone", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.create_foreign_key(
        None, "merchant_shipping_zone", "merchant_warehouse", ["warehouse_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "merchant_shipping_zone", type_="foreignkey")
    op.drop_column("merchant_shipping_zone", "updated_at")
    op.drop_column("merchant_shipping_zone", "created_at")
    op.drop_column("merchant_shipping_zone", "warehouse_id")
    # ### end Alembic commands ###
