"""Added IBAN to merchant

Revision ID: 575ce41390d2
Revises: 47bc2f712fd7
Create Date: 2025-09-05 16:42:12.188635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "575ce41390d2"
down_revision: Union[str, Sequence[str], None] = "47bc2f712fd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("iban", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "iban")
    # ### end Alembic commands ###
