"""Initial

Revision ID: 74ec8ac86ff3
Revises:
Create Date: 2025-08-29 17:32:54.808335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74ec8ac86ff3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_payment_methods",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("loan_type", sa.String(), nullable=True),
        sa.Column("loan_period_range", postgresql.INT4RANGE(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_base_payment_methods_id"), "base_payment_methods", ["id"], unique=False
    )
    op.create_table(
        "countries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("currency_code", sa.String(), nullable=False),
        sa.Column("postal_codes_range", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("legal_name", sa.String(), nullable=False),
        sa.Column("bin", sa.String(length=12), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bin"),
    )
    op.create_index(op.f("ix_merchants_id"), "merchants", ["id"], unique=False)
    op.create_index(
        op.f("ix_merchants_legal_name"), "merchants", ["legal_name"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("is_merchant", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("is_technical", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "airlinks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("moderation_status", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date_start", sa.DateTime(), nullable=True),
        sa.Column("date_end", sa.DateTime(), nullable=True),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("planned_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=True),
        sa.Column("public_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_airlinks_id"), "airlinks", ["id"], unique=False)
    op.create_table(
        "cities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("country_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.create_table(
        "customers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("default_locale", sa.String(), nullable=True),
        sa.Column("entry_merchant_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_table(
        "merchant_employee_association",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "merchant_id"),
    )
    op.create_table(
        "merchant_payment_methods",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("base_payment_method_id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_payment_method_id"],
            ["base_payment_methods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_payment_methods_id"),
        "merchant_payment_methods",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("validation_type", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_sessions_id"), "user_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_user_sessions_jti"), "user_sessions", ["jti"], unique=True)
    op.create_index(
        op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("address_line_1", sa.String(), nullable=False),
        sa.Column("address_line_2", sa.String(), nullable=True),
        sa.Column("address_line_3", sa.String(), nullable=True),
        sa.Column("country_id", sa.String(), nullable=True),
        sa.Column("city_id", sa.String(), nullable=True),
        sa.Column("creator_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    op.create_table(
        "airlink_checkout_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("airlink_id", sa.String(), nullable=False),
        sa.Column("saleor_variant_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["airlink_id"],
            ["airlinks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_airlink_checkout_items_id"),
        "airlink_checkout_items",
        ["id"],
        unique=False,
    )
    op.create_table(
        "airlink_images",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("airlink_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["airlink_id"],
            ["airlinks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_airlink_images_id"), "airlink_images", ["id"], unique=False
    )
    op.create_table(
        "fpay_configs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("merchant_payment_method_id", sa.String(), nullable=False),
        sa.Column("fpay_merchant_id", sa.String(), nullable=False),
        sa.Column("secret_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_payment_method_id"],
            ["merchant_payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fpay_configs_id"), "fpay_configs", ["id"], unique=False)
    op.create_table(
        "mfo_configs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("merchant_payment_method_id", sa.String(), nullable=False),
        sa.Column("product_code", sa.String(), nullable=True),
        sa.Column("period_range", postgresql.INT4RANGE(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_payment_method_id"],
            ["merchant_payment_methods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mfo_configs_id"), "mfo_configs", ["id"], unique=False)
    op.create_table(
        "customer_delivery_addresses",
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("address_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("customer_id", "address_id"),
    )
    op.create_table(
        "merchant_addresses",
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.Column("address_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("warehouse_saleor_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("merchant_id", "address_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merchant_addresses")
    op.drop_table("customer_delivery_addresses")
    op.drop_index(op.f("ix_mfo_configs_id"), table_name="mfo_configs")
    op.drop_table("mfo_configs")
    op.drop_index(op.f("ix_fpay_configs_id"), table_name="fpay_configs")
    op.drop_table("fpay_configs")
    op.drop_index(op.f("ix_airlink_images_id"), table_name="airlink_images")
    op.drop_table("airlink_images")
    op.drop_index(
        op.f("ix_airlink_checkout_items_id"), table_name="airlink_checkout_items"
    )
    op.drop_table("airlink_checkout_items")
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_jti"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(
        op.f("ix_merchant_payment_methods_id"), table_name="merchant_payment_methods"
    )
    op.drop_table("merchant_payment_methods")
    op.drop_table("merchant_employee_association")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    op.drop_index(op.f("ix_airlinks_id"), table_name="airlinks")
    op.drop_table("airlinks")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_merchants_legal_name"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_id"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_base_payment_methods_id"), table_name="base_payment_methods")
    op.drop_table("base_payment_methods")
    # ### end Alembic commands ###
