"""MFO loan offer outer_id

Revision ID: 881a27aa1368
Revises: 4f4b52d86cfc
Create Date: 2025-09-16 17:29:27.861561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "881a27aa1368"
down_revision: Union[str, Sequence[str], None] = "4f4b52d86cfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loan_offers", sa.Column("outer_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loan_offers", "outer_id")
    # ### end Alembic commands ###
