"""added employee profile

Revision ID: 8d119f10ec91
Revises: 8d3e660593f1
Create Date: 2025-09-18 11:29:11.487311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d119f10ec91"
down_revision: Union[str, Sequence[str], None] = "8d3e660593f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=True),
        sa.Column("profile_id", sa.String(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_profiles_id"), "employee_profiles", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_employee_profiles_user_id"),
        "employee_profiles",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_profiles_user_id"), table_name="employee_profiles")
    op.drop_index(op.f("ix_employee_profiles_id"), table_name="employee_profiles")
    op.drop_table("employee_profiles")
    # ### end Alembic commands ###
