"""pg_payment_id

Revision ID: 8d3e660593f1
Revises: 881a27aa1368
Create Date: 2025-09-17 15:09:57.949917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d3e660593f1"
down_revision: Union[str, Sequence[str], None] = "881a27aa1368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "card_requests", sa.Column("pg_payment_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_requests", "pg_payment_id")
    # ### end Alembic commands ###
