"""Added address relation to merchant_warehouse

Revision ID: 9fd0c525b881
Revises: b0e20590042b
Create Date: 2025-09-19 14:55:46.798863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd0c525b881'
down_revision: Union[str, Sequence[str], None] = 'b0e20590042b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_warehouse', sa.Column('address_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'merchant_warehouse', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchant_warehouse', type_='foreignkey')
    op.drop_column('merchant_warehouse', 'address_id')
    # ### end Alembic commands ###
