"""confirmation table

Revision ID: a442f116d327
Revises: 9fd0c525b881
Create Date: 2025-09-23 11:50:39.737383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a442f116d327'
down_revision: Union[str, Sequence[str], None] = '9fd0c525b881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saleor_order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REQUESTED', 'CONFIRMED', name='orderconfirmationstatus'), nullable=False),
    sa.Column('confirmation_code', sa.Integer(), nullable=True),
    sa.Column('confirmation_trials', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_confirmations_customer_id'), 'order_confirmations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_confirmations_id'), 'order_confirmations', ['id'], unique=False)
    op.create_index(op.f('ix_order_confirmations_merchant_id'), 'order_confirmations', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_order_confirmations_saleor_order_id'), 'order_confirmations', ['saleor_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_confirmations_saleor_order_id'), table_name='order_confirmations')
    op.drop_index(op.f('ix_order_confirmations_merchant_id'), table_name='order_confirmations')
    op.drop_index(op.f('ix_order_confirmations_id'), table_name='order_confirmations')
    op.drop_index(op.f('ix_order_confirmations_customer_id'), table_name='order_confirmations')
    op.drop_table('order_confirmations')
    # ### end Alembic commands ###
