"""Added AI response field

Revision ID: ab3e7215a3fc
Revises: e815873aad01
Create Date: 2025-09-11 18:04:15.892779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab3e7215a3fc"
down_revision: Union[str, Sequence[str], None] = "e815873aad01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("airlinks", sa.Column("ai_response", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("airlinks", "ai_response")
    # ### end Alembic commands ###
