"""Data_transactions

Revision ID: acb1d41a0858
Revises: ca4d08ec4e6a
Create Date: 2025-09-12 16:53:47.337056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acb1d41a0858"
down_revision: Union[str, Sequence[str], None] = "ca4d08ec4e6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card_requests", sa.Column("pg_order_id", sa.String(), nullable=True))
    op.add_column(
        "card_requests", sa.Column("pg_reference", sa.String(), nullable=True)
    )
    op.add_column("card_requests", sa.Column("pg_card_pan", sa.String(), nullable=True))
    op.add_column(
        "card_requests", sa.Column("pg_payment_date", sa.String(), nullable=True)
    )
    op.add_column("card_requests", sa.Column("pg_result", sa.Integer(), nullable=True))
    op.add_column(
        "card_requests", sa.Column("pg_can_reject", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "card_requests",
        sa.Column(
            "pg_ps_full_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
    )
    op.add_column(
        "card_requests",
        sa.Column("pg_net_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("card_requests", "pg_net_amount")
    op.drop_column("card_requests", "pg_ps_full_amount")
    op.drop_column("card_requests", "pg_can_reject")
    op.drop_column("card_requests", "pg_result")
    op.drop_column("card_requests", "pg_payment_date")
    op.drop_column("card_requests", "pg_card_pan")
    op.drop_column("card_requests", "pg_reference")
    op.drop_column("card_requests", "pg_order_id")
    # ### end Alembic commands ###
