"""Added company id type and registration date

Revision ID: adac1d67474d
Revises: 8d119f10ec91
Create Date: 2025-09-18 11:31:49.027297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adac1d67474d"
down_revision: Union[str, Sequence[str], None] = "8d119f10ec91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("company_id", sa.String(), nullable=True))
    op.add_column("merchants", sa.Column("company_type", sa.String(), nullable=True))
    op.add_column(
        "merchants", sa.Column("registration_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "registration_date")
    op.drop_column("merchants", "company_type")
    op.drop_column("merchants", "company_id")
    # ### end Alembic commands ###
