"""Merchant category

Revision ID: af75f8fca107
Revises: b10383475e0c
Create Date: 2025-09-02 16:25:43.333352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "af75f8fca107"
down_revision: Union[str, Sequence[str], None] = "b10383475e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_category",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("saleor_category_id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_category_id"), "merchant_category", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_merchant_category_id"), table_name="merchant_category")
    op.drop_table("merchant_category")
    # ### end Alembic commands ###
