"""selected_offer

Revision ID: b10383475e0c
Revises: 4a5cf49f34c9
Create Date: 2025-08-29 19:29:38.590410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b10383475e0c"
down_revision: Union[str, Sequence[str], None] = "4a5cf49f34c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loan_requests", sa.Column("selected_offer", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "loan_requests", "loan_offers", ["selected_offer"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "loan_requests", type_="foreignkey")
    op.drop_column("loan_requests", "selected_offer")
    # ### end Alembic commands ###
