"""Merchant Warehouse

Revision ID: b62e80841c1b
Revises: af75f8fca107
Create Date: 2025-09-02 19:10:26.035454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b62e80841c1b"
down_revision: Union[str, Sequence[str], None] = "af75f8fca107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_warehouse",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("saleor_warehouse_id", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_warehouse_id"), "merchant_warehouse", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_merchant_warehouse_id"), table_name="merchant_warehouse")
    op.drop_table("merchant_warehouse")
    # ### end Alembic commands ###
