"""Added merchant_site_carouseL-items

Revision ID: bb8f3f6090fc
Revises: 575ce41390d2
Create Date: 2025-09-05 17:46:37.372139

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bb8f3f6090fc"
down_revision: Union[str, Sequence[str], None] = "575ce41390d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
