"""Terminal for merchant

Revision ID: ca4d08ec4e6a
Revises: ab3e7215a3fc
Create Date: 2025-09-12 14:06:39.074985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca4d08ec4e6a"
down_revision: Union[str, Sequence[str], None] = "ab3e7215a3fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("merchants", sa.Column("mid", sa.String(), nullable=True))
    op.add_column("merchants", sa.Column("mcc", sa.String(), nullable=True))
    op.add_column("merchants", sa.Column("oked", sa.String(), nullable=True))
    op.add_column("merchants", sa.Column("tid", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "tid")
    op.drop_column("merchants", "oked")
    op.drop_column("merchants", "mcc")
    op.drop_column("merchants", "mid")
    # ### end Alembic commands ###
