"""Relations of Wareouses 2

Revision ID: d16b5891c4de
Revises: 54a923d9674e
Create Date: 2025-09-08 16:11:38.318609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d16b5891c4de"
down_revision: Union[str, Sequence[str], None] = "54a923d9674e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_shipping_zone_warehouse_association",
        sa.Column("shipping_zone_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipping_zone_id"],
            ["merchant_shipping_zone.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["merchant_warehouse.id"],
        ),
        sa.PrimaryKeyConstraint("shipping_zone_id", "warehouse_id"),
    )
    op.drop_constraint(
        op.f("merchant_shipping_zone_warehouse_id_fkey"),
        "merchant_shipping_zone",
        type_="foreignkey",
    )
    op.drop_column("merchant_shipping_zone", "warehouse_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchant_shipping_zone",
        sa.Column("warehouse_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("merchant_shipping_zone_warehouse_id_fkey"),
        "merchant_shipping_zone",
        "merchant_warehouse",
        ["warehouse_id"],
        ["id"],
    )
    op.drop_table("merchant_shipping_zone_warehouse_association")
    # ### end Alembic commands ###
