"""Additional relation

Revision ID: d49b798945c2
Revises: bb8f3f6090fc
Create Date: 2025-09-05 17:48:13.945175

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d49b798945c2"
down_revision: Union[str, Sequence[str], None] = "bb8f3f6090fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
