"""create notification tables

Revision ID: e815873aad01
Revises: 5e59580e9b40
Create Date: 2025-09-10 16:51:27.501215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e815873aad01"
down_revision: Union[str, Sequence[str], None] = "5e59580e9b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "template", sa.Column("purpose", sa.String(length=100), nullable=False)
    )
    op.create_unique_constraint(None, "template", ["purpose"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "template", type_="unique")
    op.drop_column("template", "purpose")
    # ### end Alembic commands ###
