"""MFO uuid and raw json response

Revision ID: f19ef672e140
Revises: 35114b4e4c53
Create Date: 2025-09-15 18:40:38.345700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f19ef672e140"
down_revision: Union[str, Sequence[str], None] = "35114b4e4c53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loan_requests", sa.Column("mfo_uuid", sa.UUID(), nullable=True))
    op.add_column(
        "loan_requests", sa.Column("raw_json_response", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loan_requests", "raw_json_response")
    op.drop_column("loan_requests", "mfo_uuid")
    # ### end Alembic commands ###
