"""Added MerchantShipping zone entity

Revision ID: f1fd3460f2f0
Revises: d49b798945c2
Create Date: 2025-09-08 14:09:33.936591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1fd3460f2f0"
down_revision: Union[str, Sequence[str], None] = "d49b798945c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_shipping_zone",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.String(), nullable=True),
        sa.Column("saleor_shipping_zone_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_shipping_zone_id"),
        "merchant_shipping_zone",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_merchant_shipping_zone_id"), table_name="merchant_shipping_zone"
    )
    op.drop_table("merchant_shipping_zone")
    # ### end Alembic commands ###
