"""New Airlink updates

Revision ID: f611d5aad2af
Revises: d16b5891c4de
Create Date: 2025-09-10 14:02:17.350417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f611d5aad2af"
down_revision: Union[str, Sequence[str], None] = "d16b5891c4de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("airlinks", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "airlinks",
        "planned_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "airlinks",
        "planned_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column("airlinks", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
