# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProductErrorCode


class AddProductToChannel(BaseModel):
    product_channel_listing_update: Optional[
        "AddProductToChannelProductChannelListingUpdate"
    ] = Field(alias="productChannelListingUpdate")


class AddProductToChannelProductChannelListingUpdate(BaseModel):
    product: Optional["AddProductToChannelProductChannelListingUpdateProduct"]
    errors: List["AddProductToChannelProductChannelListingUpdateErrors"]
    product_channel_listing_errors: List[
        "AddProductToChannelProductChannelListingUpdateProductChannelListingErrors"
    ] = Field(alias="productChannelListingErrors")


class AddProductToChannelProductChannelListingUpdateProduct(BaseModel):
    id: str
    seo_title: Optional[str] = Field(alias="seoTitle")
    seo_description: Optional[str] = Field(alias="seoDescription")
    name: str
    description: Optional[Any]
    slug: str
    created: Any
    updated_at: Any = Field(alias="updatedAt")
    charge_taxes: bool = Field(alias="chargeTaxes")
    rating: Optional[float]
    channel: Optional[str]
    description_json: Optional[Any] = Field(alias="descriptionJson")
    is_available: Optional[bool] = Field(alias="isAvailable")
    available_for_purchase: Optional[Any] = Field(alias="availableForPurchase")
    available_for_purchase_at: Optional[Any] = Field(alias="availableForPurchaseAt")
    is_available_for_purchase: Optional[bool] = Field(alias="isAvailableForPurchase")
    external_reference: Optional[str] = Field(alias="externalReference")


class AddProductToChannelProductChannelListingUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    attributes: Optional[List[str]]
    values: Optional[List[str]]
    channels: Optional[List[str]]
    variants: Optional[List[str]]


class AddProductToChannelProductChannelListingUpdateProductChannelListingErrors(
    BaseModel
):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    attributes: Optional[List[str]]
    values: Optional[List[str]]
    channels: Optional[List[str]]
    variants: Optional[List[str]]


AddProductToChannel.model_rebuild()
AddProductToChannelProductChannelListingUpdate.model_rebuild()
