# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ShippingErrorCode, ShippingMethodTypeEnum


class AddShippingMethodToChannel(BaseModel):
    shipping_method_channel_listing_update: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdate"
    ] = Field(alias="shippingMethodChannelListingUpdate")


class AddShippingMethodToChannelShippingMethodChannelListingUpdate(BaseModel):
    shipping_method: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethod"
    ] = Field(alias="shippingMethod")
    shipping_errors: List[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingErrors"
    ] = Field(alias="shippingErrors")
    errors: List["AddShippingMethodToChannelShippingMethodChannelListingUpdateErrors"]


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethod(
    BaseModel
):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    description: Optional[Any]
    type: Optional[ShippingMethodTypeEnum]
    maximum_delivery_days: Optional[int] = Field(alias="maximumDeliveryDays")
    minimum_delivery_days: Optional[int] = Field(alias="minimumDeliveryDays")
    maximum_order_price: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodMaximumOrderPrice"
    ] = Field(alias="maximumOrderPrice")
    minimum_order_price: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodMinimumOrderPrice"
    ] = Field(alias="minimumOrderPrice")
    channel_listings: Optional[
        List[
            "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListings"
        ]
    ] = Field(alias="channelListings")


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodMaximumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodMinimumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListings(
    BaseModel
):
    id: str
    channel: "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsChannel"
    maximum_order_price: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsMaximumOrderPrice"
    ] = Field(alias="maximumOrderPrice")
    minimum_order_price: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsMinimumOrderPrice"
    ] = Field(alias="minimumOrderPrice")
    price: Optional[
        "AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsPrice"
    ]


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsChannel(
    BaseModel
):
    id: str
    name: str


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsMaximumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsMinimumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListingsPrice(
    BaseModel
):
    currency: str
    amount: float


class AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingErrors(
    BaseModel
):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


class AddShippingMethodToChannelShippingMethodChannelListingUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


AddShippingMethodToChannel.model_rebuild()
AddShippingMethodToChannelShippingMethodChannelListingUpdate.model_rebuild()
AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethod.model_rebuild()
AddShippingMethodToChannelShippingMethodChannelListingUpdateShippingMethodChannelListings.model_rebuild()
