# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProductErrorCode


class AddVariantStock(BaseModel):
    product_variant_stocks_create: Optional[
        "AddVariantStockProductVariantStocksCreate"
    ] = Field(alias="productVariantStocksCreate")


class AddVariantStockProductVariantStocksCreate(BaseModel):
    bulk_stock_errors: List[
        "AddVariantStockProductVariantStocksCreateBulkStockErrors"
    ] = Field(alias="bulkStockErrors")
    errors: List["AddVariantStockProductVariantStocksCreateErrors"]


class AddVariantStockProductVariantStocksCreateBulkStockErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    attributes: Optional[List[str]]
    values: Optional[List[str]]
    index: Optional[int]


class AddVariantStockProductVariantStocksCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    attributes: Optional[List[str]]
    values: Optional[List[str]]
    index: Optional[int]


AddVariantStock.model_rebuild()
AddVariantStockProductVariantStocksCreate.model_rebuild()
