# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ShippingErrorCode


class DeleteShippingZoneByID(BaseModel):
    shipping_zone_delete: Optional["DeleteShippingZoneByIDShippingZoneDelete"] = Field(
        alias="shippingZoneDelete"
    )


class DeleteShippingZoneByIDShippingZoneDelete(BaseModel):
    shipping_errors: List["DeleteShippingZoneByIDShippingZoneDeleteShippingErrors"] = (
        Field(alias="shippingErrors")
    )
    errors: List["DeleteShippingZoneByIDShippingZoneDeleteErrors"]


class DeleteShippingZoneByIDShippingZoneDeleteShippingErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


class DeleteShippingZoneByIDShippingZoneDeleteErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


DeleteShippingZoneByID.model_rebuild()
DeleteShippingZoneByIDShippingZoneDelete.model_rebuild()
