# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import WarehouseErrorCode


class DeleteWarehouseByID(BaseModel):
    delete_warehouse: Optional["DeleteWarehouseByIDDeleteWarehouse"] = Field(
        alias="deleteWarehouse"
    )


class DeleteWarehouseByIDDeleteWarehouse(BaseModel):
    warehouse_errors: List["DeleteWarehouseByIDDeleteWarehouseWarehouseErrors"] = Field(
        alias="warehouseErrors"
    )
    errors: List["DeleteWarehouseByIDDeleteWarehouseErrors"]


class DeleteWarehouseByIDDeleteWarehouseWarehouseErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: WarehouseErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")


class DeleteWarehouseByIDDeleteWarehouseErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: WarehouseErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")


DeleteWarehouseByID.model_rebuild()
DeleteWarehouseByIDDeleteWarehouse.model_rebuild()
