# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AddressTypeEnum, CheckoutErrorCode


class DeleteCheckoutLines(BaseModel):
    checkout_lines_delete: Optional["DeleteCheckoutLinesCheckoutLinesDelete"] = Field(
        alias="checkoutLinesDelete"
    )


class DeleteCheckoutLinesCheckoutLinesDelete(BaseModel):
    errors: List["DeleteCheckoutLinesCheckoutLinesDeleteErrors"]


class DeleteCheckoutLinesCheckoutLinesDeleteErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode
    variants: Optional[List[str]]
    lines: Optional[List[str]]
    address_type: Optional[AddressTypeEnum] = Field(alias="addressType")


DeleteCheckoutLines.model_rebuild()
DeleteCheckoutLinesCheckoutLinesDelete.model_rebuild()
