# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class DisplayAvaiableCategories(BaseModel):
    categories: Optional["DisplayAvaiableCategoriesCategories"]


class DisplayAvaiableCategoriesCategories(BaseModel):
    total_count: Optional[int] = Field(alias="totalCount")
    page_info: "DisplayAvaiableCategoriesCategoriesPageInfo" = Field(alias="pageInfo")
    edges: List["DisplayAvaiableCategoriesCategoriesEdges"]


class DisplayAvaiableCategoriesCategoriesPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")
    end_cursor: Optional[str] = Field(alias="endCursor")


class DisplayAvaiableCategoriesCategoriesEdges(BaseModel):
    cursor: str
    node: "DisplayAvaiableCategoriesCategoriesEdgesNode"


class DisplayAvaiableCategoriesCategoriesEdgesNode(BaseModel):
    id: str
    seo_title: Optional[str] = Field(alias="seoTitle")
    seo_description: Optional[str] = Field(alias="seoDescription")
    name: str
    description: Optional[Any]
    slug: str
    level: int
    description_json: Optional[Any] = Field(alias="descriptionJson")
    updated_at: Any = Field(alias="updatedAt")
    parent: Optional["DisplayAvaiableCategoriesCategoriesEdgesNodeParent"]


class DisplayAvaiableCategoriesCategoriesEdgesNodeParent(BaseModel):
    id: str
    seo_title: Optional[str] = Field(alias="seoTitle")
    seo_description: Optional[str] = Field(alias="seoDescription")
    name: str
    description: Optional[Any]
    slug: str
    level: int
    description_json: Optional[Any] = Field(alias="descriptionJson")
    updated_at: Any = Field(alias="updatedAt")


DisplayAvaiableCategories.model_rebuild()
DisplayAvaiableCategoriesCategories.model_rebuild()
DisplayAvaiableCategoriesCategoriesEdges.model_rebuild()
DisplayAvaiableCategoriesCategoriesEdgesNode.model_rebuild()
