# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AddressTypeEnum, FulfillmentStatus, OrderErrorCode


class FullFillOrder(BaseModel):
    order_fulfill: Optional["FullFillOrderOrderFulfill"] = Field(alias="orderFulfill")


class FullFillOrderOrderFulfill(BaseModel):
    fulfillments: Optional[List["FullFillOrderOrderFulfillFulfillments"]]
    order_errors: List["FullFillOrderOrderFulfillOrderErrors"] = Field(
        alias="orderErrors"
    )
    errors: List["FullFillOrderOrderFulfillErrors"]
    order: Optional["FullFillOrderOrderFulfillOrder"]


class FullFillOrderOrderFulfillFulfillments(BaseModel):
    id: str
    fulfillment_order: int = Field(alias="fulfillmentOrder")
    status: FulfillmentStatus
    tracking_number: str = Field(alias="trackingNumber")
    created: Any
    status_display: Optional[str] = Field(alias="statusDisplay")


class FullFillOrderOrderFulfillOrderErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: OrderErrorCode
    warehouse: Optional[str]
    order_lines: Optional[List[str]] = Field(alias="orderLines")
    variants: Optional[List[str]]
    address_type: Optional[AddressTypeEnum] = Field(alias="addressType")


class FullFillOrderOrderFulfillErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: OrderErrorCode
    warehouse: Optional[str]
    order_lines: Optional[List[str]] = Field(alias="orderLines")
    variants: Optional[List[str]]
    address_type: Optional[AddressTypeEnum] = Field(alias="addressType")


class FullFillOrderOrderFulfillOrder(BaseModel):
    id: str


FullFillOrder.model_rebuild()
FullFillOrderOrderFulfill.model_rebuild()
