# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ShippingMethodTypeEnum, WarehouseClickAndCollectOptionEnum


class GetShippingZoneInfoByID(BaseModel):
    shipping_zone: Optional["GetShippingZoneInfoByIDShippingZone"] = Field(
        alias="shippingZone"
    )


class GetShippingZoneInfoByIDShippingZone(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    default: bool
    description: Optional[str]
    shipping_methods: Optional[
        List["GetShippingZoneInfoByIDShippingZoneShippingMethods"]
    ] = Field(alias="shippingMethods")
    warehouses: List["GetShippingZoneInfoByIDShippingZoneWarehouses"]
    channels: List["GetShippingZoneInfoByIDShippingZoneChannels"]


class GetShippingZoneInfoByIDShippingZoneShippingMethods(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    description: Optional[Any]
    type: Optional[ShippingMethodTypeEnum]
    maximum_delivery_days: Optional[int] = Field(alias="maximumDeliveryDays")
    minimum_delivery_days: Optional[int] = Field(alias="minimumDeliveryDays")
    maximum_order_price: Optional[
        "GetShippingZoneInfoByIDShippingZoneShippingMethodsMaximumOrderPrice"
    ] = Field(alias="maximumOrderPrice")
    minimum_order_price: Optional[
        "GetShippingZoneInfoByIDShippingZoneShippingMethodsMinimumOrderPrice"
    ] = Field(alias="minimumOrderPrice")
    channel_listings: Optional[
        List["GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListings"]
    ] = Field(alias="channelListings")


class GetShippingZoneInfoByIDShippingZoneShippingMethodsMaximumOrderPrice(BaseModel):
    currency: str
    amount: float


class GetShippingZoneInfoByIDShippingZoneShippingMethodsMinimumOrderPrice(BaseModel):
    currency: str
    amount: float


class GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListings(BaseModel):
    id: str
    channel: "GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsChannel"
    maximum_order_price: Optional[
        "GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsMaximumOrderPrice"
    ] = Field(alias="maximumOrderPrice")
    minimum_order_price: Optional[
        "GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsMinimumOrderPrice"
    ] = Field(alias="minimumOrderPrice")
    price: Optional[
        "GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsPrice"
    ]


class GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsChannel(
    BaseModel
):
    id: str
    name: str


class GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsMaximumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsMinimumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListingsPrice(BaseModel):
    currency: str
    amount: float


class GetShippingZoneInfoByIDShippingZoneWarehouses(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    slug: str
    email: str
    is_private: bool = Field(alias="isPrivate")
    company_name: str = Field(alias="companyName")
    click_and_collect_option: WarehouseClickAndCollectOptionEnum = Field(
        alias="clickAndCollectOption"
    )
    external_reference: Optional[str] = Field(alias="externalReference")


class GetShippingZoneInfoByIDShippingZoneChannels(BaseModel):
    id: str
    slug: str
    name: str
    is_active: bool = Field(alias="isActive")
    currency_code: str = Field(alias="currencyCode")
    has_orders: bool = Field(alias="hasOrders")


GetShippingZoneInfoByID.model_rebuild()
GetShippingZoneInfoByIDShippingZone.model_rebuild()
GetShippingZoneInfoByIDShippingZoneShippingMethods.model_rebuild()
GetShippingZoneInfoByIDShippingZoneShippingMethodsChannelListings.model_rebuild()
