# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from .base_model import BaseModel


class GetProduct(BaseModel):
    product: Optional["GetProductProduct"]


class GetProductProduct(BaseModel):
    id: str
    name: str
    slug: str
    description: Optional[Any]
    variants: Optional[List["GetProductProductVariants"]]
    metafields: Optional[Any]


class GetProductProductVariants(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    pricing: Optional["GetProductProductVariantsPricing"]
    stocks: Optional[List["GetProductProductVariantsStocks"]]


class GetProductProductVariantsPricing(BaseModel):
    price: Optional["GetProductProductVariantsPricingPrice"]


class GetProductProductVariantsPricingPrice(BaseModel):
    gross: "GetProductProductVariantsPricingPriceGross"


class GetProductProductVariantsPricingPriceGross(BaseModel):
    amount: float
    currency: str


class GetProductProductVariantsStocks(BaseModel):
    quantity: int


GetProduct.model_rebuild()
GetProductProduct.model_rebuild()
GetProductProductVariants.model_rebuild()
GetProductProductVariantsPricing.model_rebuild()
GetProductProductVariantsPricingPrice.model_rebuild()
