# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetChannelByID(BaseModel):
    channel: Optional["GetChannelByIDChannel"]


class GetChannelByIDChannel(BaseModel):
    id: str
    slug: str
    name: str
    is_active: bool = Field(alias="isActive")
    currency_code: str = Field(alias="currencyCode")
    has_orders: bool = Field(alias="hasOrders")


GetChannelByID.model_rebuild()
