# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ChannelErrorCode


class UpdateChannel(BaseModel):
    channel_update: Optional["UpdateChannelChannelUpdate"] = Field(
        alias="channelUpdate"
    )


class UpdateChannelChannelUpdate(BaseModel):
    channel_errors: List["UpdateChannelChannelUpdateChannelErrors"] = Field(
        alias="channelErrors"
    )
    errors: List["UpdateChannelChannelUpdateErrors"]
    channel: Optional["UpdateChannelChannelUpdateChannel"]


class UpdateChannelChannelUpdateChannelErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ChannelErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")
    warehouses: Optional[List[str]]


class UpdateChannelChannelUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ChannelErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")
    warehouses: Optional[List[str]]


class UpdateChannelChannelUpdateChannel(BaseModel):
    id: str


UpdateChannel.model_rebuild()
UpdateChannelChannelUpdate.model_rebuild()
