# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import WarehouseClickAndCollectOptionEnum, WarehouseErrorCode


class UpdateWarehouse(BaseModel):
    update_warehouse: Optional["UpdateWarehouseUpdateWarehouse"] = Field(
        alias="updateWarehouse"
    )


class UpdateWarehouseUpdateWarehouse(BaseModel):
    errors: List["UpdateWarehouseUpdateWarehouseErrors"]
    warehouse_errors: List["UpdateWarehouseUpdateWarehouseWarehouseErrors"] = Field(
        alias="warehouseErrors"
    )
    warehouse: Optional["UpdateWarehouseUpdateWarehouseWarehouse"]


class UpdateWarehouseUpdateWarehouseErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: WarehouseErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")


class UpdateWarehouseUpdateWarehouseWarehouseErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: WarehouseErrorCode
    shipping_zones: Optional[List[str]] = Field(alias="shippingZones")


class UpdateWarehouseUpdateWarehouseWarehouse(BaseModel):
    id: str
    name: str
    slug: str
    email: str
    is_private: bool = Field(alias="isPrivate")
    company_name: str = Field(alias="companyName")
    click_and_collect_option: WarehouseClickAndCollectOptionEnum = Field(
        alias="clickAndCollectOption"
    )
    external_reference: Optional[str] = Field(alias="externalReference")
    address: "UpdateWarehouseUpdateWarehouseWarehouseAddress"


class UpdateWarehouseUpdateWarehouseWarehouseAddress(BaseModel):
    id: str
    company_name: str = Field(alias="companyName")
    street_address_1: str = Field(alias="streetAddress1")
    street_address_2: str = Field(alias="streetAddress2")
    city: str
    city_area: str = Field(alias="cityArea")
    postal_code: str = Field(alias="postalCode")
    country_area: str = Field(alias="countryArea")
    phone: Optional[str]
    is_default_shipping_address: Optional[bool] = Field(
        alias="isDefaultShippingAddress"
    )
    is_default_billing_address: Optional[bool] = Field(alias="isDefaultBillingAddress")


UpdateWarehouse.model_rebuild()
UpdateWarehouseUpdateWarehouse.model_rebuild()
UpdateWarehouseUpdateWarehouseWarehouse.model_rebuild()
