# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ShippingErrorCode,
    ShippingMethodTypeEnum,
    WarehouseClickAndCollectOptionEnum,
    WeightUnitsEnum,
)


class UpdateShippingZone(BaseModel):
    shipping_zone_update: Optional["UpdateShippingZoneShippingZoneUpdate"] = Field(
        alias="shippingZoneUpdate"
    )


class UpdateShippingZoneShippingZoneUpdate(BaseModel):
    shipping_errors: List["UpdateShippingZoneShippingZoneUpdateShippingErrors"] = Field(
        alias="shippingErrors"
    )
    errors: List["UpdateShippingZoneShippingZoneUpdateErrors"]
    shipping_zone: Optional["UpdateShippingZoneShippingZoneUpdateShippingZone"] = Field(
        alias="shippingZone"
    )


class UpdateShippingZoneShippingZoneUpdateShippingErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


class UpdateShippingZoneShippingZoneUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ShippingErrorCode
    warehouses: Optional[List[str]]
    channels: Optional[List[str]]


class UpdateShippingZoneShippingZoneUpdateShippingZone(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    default: bool
    description: Optional[str]
    shipping_methods: Optional[
        List["UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethods"]
    ] = Field(alias="shippingMethods")
    warehouses: List["UpdateShippingZoneShippingZoneUpdateShippingZoneWarehouses"]


class UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethods(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    description: Optional[Any]
    type: Optional[ShippingMethodTypeEnum]
    maximum_delivery_days: Optional[int] = Field(alias="maximumDeliveryDays")
    minimum_delivery_days: Optional[int] = Field(alias="minimumDeliveryDays")
    maximum_order_price: Optional[
        "UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMaximumOrderPrice"
    ] = Field(alias="maximumOrderPrice")
    minimum_order_price: Optional[
        "UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMinimumOrderPrice"
    ] = Field(alias="minimumOrderPrice")
    minimum_order_weight: Optional[
        "UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMinimumOrderWeight"
    ] = Field(alias="minimumOrderWeight")
    maximum_order_weight: Optional[
        "UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMaximumOrderWeight"
    ] = Field(alias="maximumOrderWeight")


class UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMaximumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMinimumOrderPrice(
    BaseModel
):
    currency: str
    amount: float


class UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMinimumOrderWeight(
    BaseModel
):
    unit: WeightUnitsEnum
    value: float


class UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethodsMaximumOrderWeight(
    BaseModel
):
    unit: WeightUnitsEnum
    value: float


class UpdateShippingZoneShippingZoneUpdateShippingZoneWarehouses(BaseModel):
    id: str
    private_metafields: Optional[Any] = Field(alias="privateMetafields")
    metafields: Optional[Any]
    name: str
    email: str
    is_private: bool = Field(alias="isPrivate")
    company_name: str = Field(alias="companyName")
    click_and_collect_option: WarehouseClickAndCollectOptionEnum = Field(
        alias="clickAndCollectOption"
    )
    external_reference: Optional[str] = Field(alias="externalReference")
    slug: str


UpdateShippingZone.model_rebuild()
UpdateShippingZoneShippingZoneUpdate.model_rebuild()
UpdateShippingZoneShippingZoneUpdateShippingZone.model_rebuild()
UpdateShippingZoneShippingZoneUpdateShippingZoneShippingMethods.model_rebuild()
