# Generated by ariadne-codegen on 2025-09-18 16:35
# Source: app/graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class UpdateCheckoutAddresses(BaseModel):
    checkout_billing_address_update: Optional[
        "UpdateCheckoutAddressesCheckoutBillingAddressUpdate"
    ] = Field(alias="checkoutBillingAddressUpdate")
    checkout_shipping_address_update: Optional[
        "UpdateCheckoutAddressesCheckoutShippingAddressUpdate"
    ] = Field(alias="checkoutShippingAddressUpdate")


class UpdateCheckoutAddressesCheckoutBillingAddressUpdate(BaseModel):
    errors: List["UpdateCheckoutAddressesCheckoutBillingAddressUpdateErrors"]


class UpdateCheckoutAddressesCheckoutBillingAddressUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


class UpdateCheckoutAddressesCheckoutShippingAddressUpdate(BaseModel):
    errors: List["UpdateCheckoutAddressesCheckoutShippingAddressUpdateErrors"]


class UpdateCheckoutAddressesCheckoutShippingAddressUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


UpdateCheckoutAddresses.model_rebuild()
UpdateCheckoutAddressesCheckoutBillingAddressUpdate.model_rebuild()
UpdateCheckoutAddressesCheckoutShippingAddressUpdate.model_rebuild()
